cf_templates/bootstrap.yml

SystemAdministrator policy does not allow access to cloudformation
functionality. Travis needs that to validate and deploy CF templates.
In the future CI will also manage VPC, DBs, and just about everything
in AWS.

increase access for travis

---

cf_templates/bridge.yml

Create the following dynamo db resources:
* Dashboard to display dynamo SystemErrors metric[1]
* Alarm when there is are SystemErrors
* A SNS topic with an email endpoint for the alarm
[1] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/dynamo-metricscollected.html

Add Dynamodb resources for bridge

---

cf_templates/bootstrap.yml

Setup AWS policy to enforce MFA on Bridge account. The policy for this
is from the AWS tutorial[1].
[1] https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_users-self-manage-mfa-and-creds.html#tutorial_mfa_step1

IT-239: Enforce multi factor authentication

---

cf_templates/bridge.yml

Currently we providing sumo logic with the heroku (admin) user to
allow it to read logs from our S3 buckets.  That's not a good idea
because heroku user has too much access.  This creates a specific
service user for sumo logic so that it will only have read access
to our S3 buckets because that's all it really needs.

Create user for integration with sumo logic

---

cf_templates/bridge.yml

The Logging Service Group (aka Sumo logic) does not need access to
all buckets, it only  needs access to the elastic beanstalk bucket[1]
(i.e. elasticbeanstalk-region-account-id). Create a custom access policy
for to restrict access only to that bucket.
[1] https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.logging.html#health-logs-s3location

Restrict logging service access

---

cf_templates/bridge.yml

Allow logging service group to access EB logs folder and all sub
folders.

Fix EB logs access

---

cf_templates/bridge.yml

Sumo likes the policy to be 'arn:aws:s3:::$BUCKET_NAME' instead
of 'arn:aws:s3:::$BUCKET_NAME/AWSLogs/$ACCOUNT_ID' otherwis it
complained about not having the listing permission on the bucket.

Fix logging service managed policy

---

cf_templates/bridge.yml

enabling IsMultiRegionTrail causes CF deployment to fail with error
"Multi-Region trail must include global service events".

remove cloudtrail IsMultiRegionTrail param

---

cf_templates/bridge.yml

Allow poeple who manage AWS to assume the admin role and thus
get admin access to the AWS account.

Allow aws managers to assume admin role

---

cf_templates/bridge.yml

The enforce mfa policy lives in the bootstrap.yml which does not
get automatically deployed by travis. Moving it to the bridge.yml
file so that it gets updated by travis.
Note- this is the 1st change in a series to move this policy.
We need to duplcate the policy and then delete the old one
(in bootstrap.yml) in a follow on change.

Move enforce mfa policy to bridge.yml

---

deploy_infra.sh
update_cf_stack.sh

Instead of deploying the cloudformation template from a local file
we upload the file to an S3 bucket first then deploy with a reference
to file in the bucket.
Note- The bucket was previously created with CF code[1]
[1] https://github.com/Sage-Bionetworks/Bridge-infra/blob/develop/cf_templates/bridge.yml#L395

BRIDGE-2029: refactor CF deployment

---

cf_templates/bridge.yml

Setup a developer user group that allows developers access to AWS
resources.  The only restriction is to deny deletion of dynamo
tables/items and modificaiton of IAM resources.

Setup a developer user group

---

cf_templates/bridge.yml

Do not allow the developer group to delete rds instances.
If you need to delete a db instance then you must take the
extra step of assuming the admin role.

Revoke delete rds instance permission

---

cf_templates/bridge.yml

There's no reason to deny developers from deleting DDB items. In fact, this is sometimes necessary for ops and testing.

Remove DDB DeleteItem from deny list

---

cf_templates/bridge.yml

The only way to restrict deletion of dynamodb indexes is to
deny the UpdateTable operation.  Users will now need to elevate
to the admin role to update dynamodb tables.

BRIDGE-2041: revoke access to update dynamo tables

---

cf_templates/bridge.yml

Travis deploys CF templates asyncronously using the AWS CLI.  It will
only report whether the `aws cloudformation update-stack` CLI command
failed.  The stack update process happens in AWS and travis does not
have visibility into that process so it cannot report whether the stack
update actually failed.  The current AWS recommended[1] approach to
getting CF deployment notifications is to use a lambda function.
[1] https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-rollback-email/

BRIDGE-2049: Setup notification for CF deployments

---

cf_templates/bridge.yml

SNS policy resource does not allow configs for log actions.  Change to
an IAM managed.

Fix cloudwatch topic policy

---

cf_templates/bridge.yml

* Create an "AWSIAMiOSDevelopersGroup" in cloudformation to replace the
existing manually create "iosAppsUpdateGroup".
* Create a "AWSIAMiOSBucketManagedPolicy" in cloudformation to replace
the manually created "IosAppsCloudfrontPolicy"
IAM does not support object level permissions for cloudfront which means
we cannot give access to just one cloudfront endpoint.  It's either full
or none.
[1] https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html

Manage ios groups and policies with cloudformation

---

cf_templates/bridge.yml

The lambda to monitor cloudformation deployments would not trigger
because it was missing a policy to allow SNS to invoke it.

add lambda invocation policy

---

cf_templates/bridge.yml

Create a VPN security group to allow the Sage VPN to provide access
to any AWS resources that have this security group attached to it.

Setup a VPN security group

---

cf_templates/aws-default-vpc.yml

Bridge prod app is running in an AWS default VPC.  "Default" meaning that it
is the default VPC that comes with every AWS account.  Add a CF template
that can be used to re-create the "default" VPC if anything bad were to occur.
Also since bridge dev infra should be a mirror of prod we use this
template to create a VPC for bridge dev with a unique CIDR.  Our VPN
requires that every VPC have a unique CIDR.

Add CF template for default VPC

---

templates/bridge.yaml

Travis will alert us when sceptre fails to deploy CF templates
therefore we no longer need notifications from AWS.

Remvoe CF failed deployment notifications

---

config/prod/guardduty-member.yaml

We need to get the template from admincentral account before
we can create the stack.

Get template before creating stack

---

templates/bridge.yaml

The admin role is not mean to be used with EC2 instances so we
remove the instance profile.

remove instance profile

---

templates/bridge.yaml

AWS doc says that the a valid statistic for SMSMonthToDateSpentUSD
metric is 'Maximum'.
ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/sns-metricscollected.html

update statistics for sms spend alarm

---

templates/bridge.yaml

AWS config reports non-compliance in all our aws accounts due to
a misconfigured aws config rule.
In each aws account we have setup cloudtrail to send logs to a
central S3 bucket in our aws org-sagebase-logcentral account
(essentials-awss3cloudtrailbucket-1jz6pf8dzid7r). However the
aws config rule was setup to look for the cloudtrail logs in a
local bucket.
To fix the issue we re-configure the config rule to look for
logs in the central s3 bucket.

[it-395] Fix aws config non-compliance

---

templates/bridge.yaml

Add a alarm to notify when there are failures to publish
SMS messages to phone numbers. Also added a dashboard view
for this metric.

[BRIDGE-2313] Setup DirectPublishToPhoneNumberFailure alarm

---

templates/iam-policies.yaml
templates/prod/jumpcloud-idp.yaml

This PR is to implement request by bridge team.
Bridge Prod permissions:
* alx and dwayne have admin permissions (no restrictions)
* alx, dwayne and interns have developer permissions (no
restrictions, except:
no write access to IAM
no delete access to dynamo
no delete access to rds
No changes to Bridge Dev account.
* alx and dwayne have admin permissions(no restrictions)
* everyone else has developer permissions (no restrictions
except:
no write access to IAM

[IT-913] Update BridgeProd developer permissions

---

config/prod/tgw-spoke-BridgeServer2-vpc.yaml

This setup will allow using the new AWS client VPN to access private resources
in the production BridgeServer2-vpc
depends on Sage-Bionetworks/transit-infra#23

[IT-1003] & [IT-1004] setup VPN access to bridge resources

---

templates/develop/jumpcloud-idp.yaml

BridgeDev developers need access to several various AWS Services. This is the Dev account, so there's no risk to production data. Preferably get this pushed out Friday or Monday so that Kelly can access her test data in AWS.

BridgeDev developers permissions

---

config/develop/bridge-develop.yaml
config/develop/peer-vpn-bridge-develop.yaml

bridge-develp vpc was created (a long time ago) as a mirror for the old bridge
prod vpc that only contained public subnets. It was created with the intention
of moving bridgedev env to the AWS bridge dev account. Since then @DwayneJengSage
moved bridge app into a new prod VPC with public & private subnets. The new
"BridgeServer2-develop-vpc" was created to mirror that new prod VPC. That means
that "bridge-develop" vpc is obsolete. To clear up the confusion I we delete
the obsolete "bridge-develop" vpc and its peering connection.

[IT-1053] Remove obsolete VPC and peering

---

config/develop/peer-vpn-BridgeServer2-develop.yaml

Peering will allow access to BridgeServer2-develop-vpc resources
from the Sage VPN.
depends on https://github.com/Sage-Bionetworks/admincentral-infra/pull/103
and also depends on configuration of sophos VPN.

[IT-1053] peering to BridgeServer2-develop-vpc

---

config/develop/BridgeServer2-vpc.yaml
config/develop/bridge.yaml
config/develop/peer-vpn-BridgeServer2-develop.yaml
config/prod/bridge.yaml

VPC was tested locally and is already in our BridgeDev AWS account. These templates (should) match what's currently in AWS.

Add Bridge VPC to develop
